#!/bin/sh
# Auto-detect DNS resolver from container's resolv.conf
# Docker uses 127.0.0.11, Podman uses network gateway (e.g., 10.89.0.1)
set -e

# Extract first nameserver from resolv.conf
NGINX_RESOLVER=$(grep -m1 '^nameserver' /etc/resolv.conf | awk '{print $2}')

# Fallback to Docker DNS if not found
NGINX_RESOLVER="${NGINX_RESOLVER:-127.0.0.11}"

echo "Using DNS resolver: $NGINX_RESOLVER"

# Export for envsubst
export NGINX_RESOLVER

# Configurable upstream hosts — defaults match container service names.
# Override in environments where the API runs on the host (e.g. CI).
UPSTREAM_API_HOST="${UPSTREAM_API_HOST:-guideai-api}"
UPSTREAM_API_PORT="${UPSTREAM_API_PORT:-8000}"
UPSTREAM_WEB_CONSOLE_HOST="${UPSTREAM_WEB_CONSOLE_HOST:-web-console}"
UPSTREAM_WEB_CONSOLE_PORT="${UPSTREAM_WEB_CONSOLE_PORT:-5173}"
export UPSTREAM_API_HOST UPSTREAM_API_PORT UPSTREAM_WEB_CONSOLE_HOST UPSTREAM_WEB_CONSOLE_PORT

# Run envsubst on template to generate actual nginx.conf
envsubst '$NGINX_RESOLVER $UPSTREAM_API_HOST $UPSTREAM_API_PORT $UPSTREAM_WEB_CONSOLE_HOST $UPSTREAM_WEB_CONSOLE_PORT' < /etc/nginx/templates/nginx.conf.template > /etc/nginx/nginx.conf

# -------------------------------------------------------------------------
# Optional TLS configuration
# -------------------------------------------------------------------------
# When NGINX_SSL_CERT and NGINX_SSL_KEY point to valid files, the gateway
# will also listen on 443 with TLS.  When they are absent, empty include
# files are written so the `include` directives in nginx.conf are no-ops.
#
# Set NGINX_SSL_REDIRECT=true to add a separate server block that
# redirects HTTP (port 80) to HTTPS (port 443).  Disabled by default
# so dev environments keep working on plain HTTP.
# -------------------------------------------------------------------------
mkdir -p /etc/nginx/conf.d

if [ -n "$NGINX_SSL_CERT" ] && [ -n "$NGINX_SSL_KEY" ] \
   && [ -f "$NGINX_SSL_CERT" ] && [ -f "$NGINX_SSL_KEY" ]; then

    echo "TLS enabled: cert=$NGINX_SSL_CERT key=$NGINX_SSL_KEY"
    cat > /etc/nginx/conf.d/tls.conf <<EOF
# --- Auto-generated by docker-entrypoint.sh ---
listen 443 ssl;
listen [::]:443 ssl;

ssl_certificate     $NGINX_SSL_CERT;
ssl_certificate_key $NGINX_SSL_KEY;

ssl_protocols TLSv1.2 TLSv1.3;
ssl_ciphers HIGH:!aNULL:!MD5;
ssl_prefer_server_ciphers on;
ssl_session_cache shared:SSL:10m;
ssl_session_timeout 10m;

add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
EOF

    # Optional HTTP→HTTPS redirect
    if [ "${NGINX_SSL_REDIRECT}" = "true" ]; then
        echo "TLS redirect enabled: HTTP→HTTPS"
        cat > /etc/nginx/conf.d/tls-redirect.conf <<EOF
# --- Auto-generated by docker-entrypoint.sh ---
server {
    listen 80;
    listen [::]:80;
    server_name _;
    return 301 https://\$host\$request_uri;
}
EOF
    else
        : > /etc/nginx/conf.d/tls-redirect.conf
    fi
else
    echo "TLS disabled: NGINX_SSL_CERT/NGINX_SSL_KEY not set or files missing"
    : > /etc/nginx/conf.d/tls.conf
    : > /etc/nginx/conf.d/tls-redirect.conf
fi

# Start nginx
exec nginx -g 'daemon off;'
