"""Bootstrap Service — coordinates workspace profiling and knowledge pack setup.

This service handles the complete initialization flow for new projects:
1. Detect workspace signals to suggest an appropriate profile
2. Select a matching knowledge pack based on the profile
3. Generate profile-scoped config/primer files (AGENTS.md, .guideai.yaml)

Part of E2 (GUIDEAI-276) of the Knowledge Pack architecture.
See docs/GUIDEAI_KNOWLEDGE_PACK_ARCHITECTURE.md §6.3, §8.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass
from pathlib import Path
from typing import TYPE_CHECKING, Optional

from guideai.bootstrap.detector import WorkspaceDetector
from guideai.bootstrap.profile import ProfileDetectionResult, WorkspaceProfile

if TYPE_CHECKING:
    from guideai.knowledge_pack.activation_service import ActivationService

logger = logging.getLogger(__name__)


# =============================================================================
# Profile-to-Pack Mappings
# =============================================================================

# Default knowledge pack for each workspace profile
_PROFILE_DEFAULT_PACKS: dict[WorkspaceProfile, str] = {
    WorkspaceProfile.SOLO_DEV: "solo-developer",
    WorkspaceProfile.GUIDEAI_PLATFORM: "guideai-platform",
    WorkspaceProfile.TEAM_COLLAB: "team-collaboration",
    WorkspaceProfile.EXTENSION_DEV: "extension-developer",
    WorkspaceProfile.API_BACKEND: "api-backend",
    WorkspaceProfile.COMPLIANCE_SENSITIVE: "compliance-sensitive",
}

# Profile-specific AGENTS.md templates
_PROFILE_PRIMERS: dict[WorkspaceProfile, str] = {
    WorkspaceProfile.SOLO_DEV: """# Agent Handbook

> Quick-start instructions for AI coding assistants working in this project.

## 🎭 Role: Student (Default)

Follow established patterns. Retrieve behaviors before tasks using:
```bash
guideai behaviors get-for-task "<describe your task>" --role Student
```

## 🔧 Key Behaviors

| Trigger | Behavior |
|---------|----------|
| logging, telemetry | `behavior_use_raze_for_logging` |
| secrets, credentials | `behavior_prevent_secret_leaks` |
| git workflow | `behavior_git_governance` |

## ✅ Checklist

1. Run pre-commit before pushing
2. Use descriptive variable names
3. Add tests for new functionality

---
_Generated by GuideAI bootstrap for solo-dev profile._
""",
    WorkspaceProfile.GUIDEAI_PLATFORM: """# Agent Handbook

> **TL;DR**: **ALWAYS retrieve behaviors before starting any task using GuideAI MCP tools.**
> Log with Raze. Manage environments with Amprealize. Extract reusable code to `packages/`.
> Never hardcode secrets. Run `pre-commit` before pushing. **Cite both behavior AND role in your work.**

---

## 🚨 MANDATORY: Retrieve Behaviors Before Every Task

```bash
# MCP (preferred)
mcp_guideai_behaviors_getfortask(task_description="<describe your task>", role="Student")

# CLI fallback
guideai behaviors get-for-task "<describe your task>" --role Student
```

## 🎭 Agent Roles

| Role | Responsibility |
|------|----------------|
| **Student** 📖 | Routine tasks following established patterns |
| **Teacher** 🎓 | Creating examples, documentation, validation |
| **Strategist** 🧠 | Novel problems, pattern extraction, architecture |

## 🎯 Quick Triggers

| Keywords | Behavior | Role |
|----------|----------|------|
| MCP tool, IDE extension | `behavior_prefer_mcp_tools` | 📖 Student |
| logging, telemetry | `behavior_use_raze_for_logging` | 📖 Student |
| environment, container | `behavior_use_amprealize_for_environments` | 📖 Student |
| secret, credential | `behavior_prevent_secret_leaks` | 📖 Student |
| pattern observed 3+ times | Propose new behavior | 🧠 Strategist |

---
_Generated by GuideAI bootstrap for guideai-platform profile._
""",
    WorkspaceProfile.TEAM_COLLAB: """# Agent Handbook

> Team collaboration guidelines for AI coding assistants.

## 🎭 Roles

This workspace uses team collaboration patterns. Follow CODEOWNERS for review routing.

## 🔄 PR Workflow

1. Create feature branches: `feature/<short-desc>`
2. Follow PR template in `.github/pull_request_template.md`
3. Request review from CODEOWNERS
4. Squash and merge with conventional commit message

## 🔧 Key Behaviors

| Trigger | Behavior |
|---------|----------|
| git workflow, branching | `behavior_git_governance` |
| code review, PR | `behavior_conduct_code_review` |
| documentation | `behavior_update_docs_after_changes` |

## ✅ Checklist

1. Run pre-commit before pushing
2. Write tests for new functionality
3. Update docs when APIs change
4. Follow CODEOWNERS review requirements

---
_Generated by GuideAI bootstrap for team-collab profile._
""",
    WorkspaceProfile.EXTENSION_DEV: """# Agent Handbook

> Guidelines for VS Code extension development.

## 🎭 Role: Student (Default)

Follow established extension patterns. Reference existing panels/providers.

## 🔧 Key Behaviors

| Trigger | Behavior |
|---------|----------|
| VS Code extension, webview | `behavior_integrate_vscode_extension` |
| git workflow | `behavior_git_governance` |
| test strategy | `behavior_design_test_strategy` |

## 📁 Architecture

- `src/panels/` — Webview panels
- `src/providers/` — Tree data providers
- `src/client/` — API clients (MCP, Raze, etc.)

## ✅ Checklist

1. Use TypeScript strict mode
2. Register disposables in `activate()`
3. Add telemetry with RazeClient
4. Test with Extension Test Runner

---
_Generated by GuideAI bootstrap for extension-dev profile._
""",
    WorkspaceProfile.API_BACKEND: """# Agent Handbook

> Guidelines for API backend development.

## 🎭 Role: Student (Default)

Follow established API patterns. Use Pydantic models for validation.

## 🔧 Key Behaviors

| Trigger | Behavior |
|---------|----------|
| API design, OpenAPI | `behavior_design_api_contract` |
| logging, telemetry | `behavior_use_raze_for_logging` |
| database, migrations | `behavior_migrate_postgres_schema` |
| secrets, credentials | `behavior_prevent_secret_leaks` |

## 🏗️ API Standards

- Use OpenAPI 3.x specs
- Version APIs in path (`/v1/`)
- Validate requests with Pydantic
- Return consistent error formats

## ✅ Checklist

1. Design schema first, then implement
2. Add input validation and sanitization
3. Write integration tests for endpoints
4. Document breaking changes

---
_Generated by GuideAI bootstrap for api-backend profile._
""",
    WorkspaceProfile.COMPLIANCE_SENSITIVE: """# Agent Handbook

> Guidelines for compliance-sensitive development.

## 🚨 Critical Rules

| Rule | Behavior |
|------|----------|
| Never hardcode secrets | `behavior_prevent_secret_leaks` |
| Run pre-commit before push | `behavior_prevent_secret_leaks` |
| Audit-log data changes | `behavior_align_storage_layers` |
| Review security posture | `behavior_lock_down_security_surface` |

## 🎭 Roles

- **Student** 📖: Follow compliance runbooks strictly
- **Teacher** 🎓: Create compliance documentation
- **Strategist** 🧠: Post-incident reviews, threat modeling

## 🔧 Key Behaviors

| Trigger | Behavior |
|---------|----------|
| secret, credential, leak | `behavior_prevent_secret_leaks`, `behavior_rotate_leaked_credentials` |
| CORS, auth, security | `behavior_lock_down_security_surface` |
| incident, outage | `behavior_triage_incident` |
| postmortem, RCA | `behavior_write_postmortem` |

## ✅ Checklist

1. Review SECURITY.md before changes
2. Check policy/ directory for requirements
3. Run `scripts/scan_secrets.sh` before PRs
4. Document all data handling changes

---
_Generated by GuideAI bootstrap for compliance-sensitive profile._
""",
}


# =============================================================================
# Bootstrap Result
# =============================================================================


@dataclass
class BootstrapResult:
    """Result of running the bootstrap process."""

    # Detection results
    profile: WorkspaceProfile
    detection_result: ProfileDetectionResult

    # Pack info
    pack_id: str
    pack_version: str

    # Files generated
    files_written: list[str]

    # Warnings/notes
    notes: list[str]

    def to_dict(self) -> dict:
        """Convert to JSON-serializable dict."""
        return {
            "profile": self.profile.value,
            "detection": self.detection_result.to_dict(),
            "pack_id": self.pack_id,
            "pack_version": self.pack_version,
            "files_written": self.files_written,
            "notes": self.notes,
        }


# =============================================================================
# Bootstrap Service
# =============================================================================


class BootstrapService:
    """Orchestrates workspace detection, pack selection, and primer generation.

    The service coordinates three phases:
    1. **Detection**: Analyze workspace signals to suggest profile
    2. **Pack Selection**: Map profile to appropriate knowledge pack
    3. **Primer Generation**: Write AGENTS.md and config files

    Example usage:
        >>> service = BootstrapService()
        >>> result = service.bootstrap(Path("."))
        >>> print(f"Profile: {result.profile.value}, Pack: {result.pack_id}")
    """

    def __init__(
        self,
        detector: Optional[WorkspaceDetector] = None,
        activation_service: Optional["ActivationService"] = None,
    ) -> None:
        """Initialize bootstrap service.

        Parameters
        ----------
        detector:
            WorkspaceDetector instance. Created if not provided.
        activation_service:
            Optional ActivationService for recording pack activations.
            If not provided, activations are not persisted to DB.
        """
        self._detector = detector or WorkspaceDetector()
        self._activation_service = activation_service

    # =========================================================================
    # Core API
    # =========================================================================

    def bootstrap(
        self,
        workspace: Path,
        *,
        profile: Optional[WorkspaceProfile] = None,
        pack_id: Optional[str] = None,
        pack_version: str = "latest",
        skip_detection: bool = False,
        skip_pack: bool = False,
        skip_primer: bool = False,
        workspace_id: Optional[str] = None,
    ) -> BootstrapResult:
        """Run the full bootstrap process for a workspace.

        Parameters
        ----------
        workspace:
            Path to workspace root directory.
        profile:
            Explicit profile override. If None, auto-detect.
        pack_id:
            Explicit pack ID. If None, use profile default.
        pack_version:
            Pack version to activate.
        skip_detection:
            If True, skip signal detection (use provided profile or default).
        skip_pack:
            If True, skip pack activation.
        skip_primer:
            If True, skip AGENTS.md generation.
        workspace_id:
            Optional workspace ID for activation tracking.

        Returns
        -------
        BootstrapResult:
            Complete result including profile, pack, and generated files.
        """
        notes: list[str] = []
        files_written: list[str] = []

        # Phase 1: Detection
        if skip_detection and profile:
            detection_result = ProfileDetectionResult(
                profile=profile,
                confidence=1.0,
                signals=[],
                is_ambiguous=False,
            )
            notes.append("Detection skipped (explicit profile provided)")
        else:
            detection_result = self._detector.detect(workspace)
            if profile and profile != detection_result.profile:
                notes.append(
                    f"Profile override: detected {detection_result.profile.value}, "
                    f"using {profile.value}"
                )
                detection_result = ProfileDetectionResult(
                    profile=profile,
                    confidence=detection_result.confidence,
                    signals=detection_result.signals,
                    is_ambiguous=False,
                )
            elif detection_result.is_ambiguous:
                notes.append(
                    f"Detection was ambiguous between profiles. "
                    f"Using {detection_result.profile.value} as default."
                )

        final_profile = profile or detection_result.profile

        # Phase 2: Pack Selection
        final_pack_id = pack_id or _PROFILE_DEFAULT_PACKS.get(
            final_profile, "solo-developer"
        )

        if not skip_pack and self._activation_service:
            try:
                ws_id = workspace_id or str(workspace.resolve())
                self._activation_service.activate_pack(
                    workspace_id=ws_id,
                    pack_id=final_pack_id,
                    version=pack_version,
                    profile=final_profile.value,
                    auto_deactivate=True,
                )
                notes.append(f"Activated pack {final_pack_id}@{pack_version}")
            except Exception as e:
                logger.warning(f"Failed to activate pack: {e}")
                notes.append(f"Pack activation failed: {e}")
        elif skip_pack:
            notes.append("Pack activation skipped")

        # Phase 3: Primer Generation
        if not skip_primer:
            primer_path = self.generate_primer(workspace, final_profile)
            if primer_path:
                files_written.append(str(primer_path))
                notes.append(f"Generated {primer_path.name}")

        return BootstrapResult(
            profile=final_profile,
            detection_result=detection_result,
            pack_id=final_pack_id,
            pack_version=pack_version,
            files_written=files_written,
            notes=notes,
        )

    def detect(self, workspace: Path) -> ProfileDetectionResult:
        """Run only the detection phase.

        Convenience method for detection-only workflows.
        """
        return self._detector.detect(workspace)

    # =========================================================================
    # Primer Generation
    # =========================================================================

    def generate_primer(
        self,
        workspace: Path,
        profile: WorkspaceProfile,
        *,
        filename: str = "AGENTS.md",
        overwrite: bool = False,
    ) -> Optional[Path]:
        """Generate a profile-specific AGENTS.md primer file.

        Parameters
        ----------
        workspace:
            Workspace root directory.
        profile:
            Profile to use for template selection.
        filename:
            Output filename (default: AGENTS.md).
        overwrite:
            If False and file exists, return None without writing.

        Returns
        -------
        Path to written file, or None if skipped.
        """
        output_path = workspace / filename

        if output_path.exists() and not overwrite:
            logger.info(f"{filename} already exists, skipping primer generation")
            return None

        template = _PROFILE_PRIMERS.get(profile)
        if not template:
            logger.warning(f"No primer template for profile {profile.value}")
            return None

        output_path.write_text(template, encoding="utf-8")
        logger.info(f"Generated {filename} for {profile.value} profile")
        return output_path

    def get_pack_for_profile(self, profile: WorkspaceProfile) -> str:
        """Get the default knowledge pack ID for a profile."""
        return _PROFILE_DEFAULT_PACKS.get(profile, "solo-developer")

    def get_primer_template(self, profile: WorkspaceProfile) -> Optional[str]:
        """Get the AGENTS.md template for a profile."""
        return _PROFILE_PRIMERS.get(profile)
